"""
Layer 2: Metadata Service
C2PA and EXIF Metadata Analysis
"""

import io
import json
from typing import Dict, Any, List, Optional
from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS

# C2PA is an optional import (might not be installed)
try:
    from c2pa import Reader

    C2PA_AVAILABLE = True
except ImportError:
    C2PA_AVAILABLE = False


class MetadataService:
    """Image Metadata Analysis Service"""

    # AI Tool Signature Patterns
    AI_TOOL_SIGNATURES = [
        # Software Names
        "midjourney",
        "dall-e",
        "dall·e",
        "stable diffusion",
        "stability.ai",
        "novelai",
        "leonardo.ai",
        "runway",
        "firefly",
        "adobe firefly",
        "imagen",
        "dreamstudio",
        "nightcafe",
        "artbreeder",
        "craiyon",
        "bluewillow",
        "playground ai",
        "ideogram",
        "flux",
        # General AI Related Keywords
        "ai generated",
        "ai-generated",
        "generated by ai",
        "artificial intelligence",
        "machine learning generated",
        "synthetic image",
        "diffusion model",
    ]

    def analyze(self, image_bytes: bytes, filename: str) -> Dict[str, Any]:
        """
        Comprehensive Image Metadata Analysis
        """
        result = {
            "has_c2pa": False,
            "c2pa_info": None,
            "exif_data": None,
            "ai_tool_signatures": [],
            "software_used": None,
            "creation_date": None,
            "image_info": None,
            "exif_authenticity_score": 0.0,
            "exif_inconsistencies": [],
        }

        # 1. EXIF Analysis
        exif_result = self._extract_exif(image_bytes)
        result["exif_data"] = exif_result.get("exif")
        result["software_used"] = exif_result.get("software")
        result["creation_date"] = exif_result.get("creation_date")
        result["image_info"] = exif_result.get("image_info")

        # 2. C2PA Analysis
        if C2PA_AVAILABLE:
            c2pa_result = self._analyze_c2pa(image_bytes, filename)
            result["has_c2pa"] = c2pa_result.get("has_c2pa", False)
            result["c2pa_info"] = c2pa_result.get("info")

        # 3. AI Tool Signature Inspection
        result["ai_tool_signatures"] = self._detect_ai_signatures(result)

        # 4. EXIF Authenticity Score Calculation
        result["exif_authenticity_score"] = self._calculate_exif_authenticity_score(
            result["exif_data"]
        )

        # 5. EXIF Abnormal Pattern Detection
        result["exif_inconsistencies"] = self._detect_exif_inconsistencies(
            result["exif_data"]
        )

        return result

    def _extract_exif(self, image_bytes: bytes) -> Dict[str, Any]:
        """Extract EXIF Metadata"""
        result = {"exif": {}, "software": None, "creation_date": None, "image_info": {}}

        try:
            img = Image.open(io.BytesIO(image_bytes))

            # Basic Image Info
            result["image_info"] = {
                "format": img.format,
                "mode": img.mode,
                "size": {"width": img.width, "height": img.height},
            }

            # Extract EXIF Data
            exif_data = img._getexif()
            if exif_data:
                for tag_id, value in exif_data.items():
                    tag = TAGS.get(tag_id, tag_id)

                    # Convert tag to string (Handle integer tag IDs)
                    tag_key = str(tag)

                    # Exclude binary data
                    if isinstance(value, bytes):
                        continue

                    # Special Handling
                    if tag == "Software":
                        result["software"] = str(value)
                    elif tag in ["DateTime", "DateTimeOriginal", "DateTimeDigitized"]:
                        result["creation_date"] = str(value)

                    result["exif"][tag_key] = (
                        str(value) if not isinstance(value, (int, float)) else value
                    )

            # Additional metadata such as PNG tEXt chunks
            if hasattr(img, "info") and img.info:
                for key, value in img.info.items():
                    if isinstance(value, str) and key not in result["exif"]:
                        result["exif"][f"PNG_{key}"] = value

                        # parameters field (Stable Diffusion, etc.)
                        if key.lower() == "parameters":
                            result["exif"]["sd_parameters"] = value

        except Exception as e:
            result["error"] = str(e)

        return result

    def _analyze_c2pa(self, image_bytes: bytes, filename: str) -> Dict[str, Any]:
        """Analyze C2PA Content Credentials"""
        result = {"has_c2pa": False, "info": None}

        if not C2PA_AVAILABLE:
            result["error"] = "c2pa-python not installed"
            return result

        try:
            # Attempt to read C2PA manifest
            reader = Reader.from_stream("image/jpeg", io.BytesIO(image_bytes))

            if reader:
                result["has_c2pa"] = True

                # Extract manifest info
                manifest_json = reader.json()
                manifest_data = json.loads(manifest_json)

                result["info"] = {
                    "active_manifest": manifest_data.get("active_manifest"),
                    "manifests": list(manifest_data.get("manifests", {}).keys()),
                }

                # Check AI generation related assertions
                for manifest_id, manifest in manifest_data.get("manifests", {}).items():
                    assertions = manifest.get("assertions", [])
                    for assertion in assertions:
                        label = assertion.get("label", "")
                        if "ai" in label.lower() or "generative" in label.lower():
                            result["info"]["ai_related_assertions"] = result[
                                "info"
                            ].get("ai_related_assertions", [])
                            result["info"]["ai_related_assertions"].append(assertion)

        except Exception as e:
            # Images without C2PA raise an exception normally
            result["error"] = str(e) if "no manifest" not in str(e).lower() else None

        return result

    def _detect_ai_signatures(self, metadata_result: Dict[str, Any]) -> List[str]:
        """Detect AI Tool Signatures in Metadata"""
        detected = []

        # Fields to check
        text_to_check = []

        if metadata_result.get("software_used"):
            text_to_check.append(metadata_result["software_used"])

        if metadata_result.get("exif_data"):
            for key, value in metadata_result["exif_data"].items():
                if isinstance(value, str):
                    text_to_check.append(value)

        if metadata_result.get("c2pa_info"):
            text_to_check.append(json.dumps(metadata_result["c2pa_info"]))

        # Signature Matching
        combined_text = " ".join(text_to_check).lower()

        for signature in self.AI_TOOL_SIGNATURES:
            if signature.lower() in combined_text:
                detected.append(signature)

        return list(set(detected))  # Remove duplicates

    def _calculate_exif_authenticity_score(
        self, exif_data: Optional[Dict[str, Any]]
    ) -> float:
        """
        Calculate EXIF Data Authenticity Score (0.0 ~ 1.0)
        Higher score indicates higher probability of image taken with a real camera
        """
        if not exif_data:
            return 0.0

        score = 0.0
        max_score = 0.0

        # 1. Camera Info Exists (Very Important)
        camera_fields = ["Make", "Model"]
        for field in camera_fields:
            max_score += 0.25
            if field in exif_data:
                value = str(exif_data[field]).lower()
                # Check real camera manufacturers
                real_cameras = [
                    "canon",
                    "nikon",
                    "sony",
                    "fujifilm",
                    "olympus",
                    "panasonic",
                    "leica",
                    "pentax",
                    "hasselblad",
                    "phase one",
                    "apple",
                    "samsung",
                    "google",
                    "huawei",
                ]
                if any(brand in value for brand in real_cameras):
                    score += 0.25

        # 2. Shooting Settings Exist (Important)
        exposure_fields = ["ExposureTime", "FNumber", "ISOSpeedRatings", "FocalLength"]
        for field in exposure_fields:
            max_score += 0.1
            if field in exif_data:
                score += 0.1

        # 3. Time Info Exists
        time_fields = ["DateTime", "DateTimeOriginal", "DateTimeDigitized"]
        has_time = any(field in exif_data for field in time_fields)
        max_score += 0.1
        if has_time:
            score += 0.1

        # 4. Lens Info Exists
        lens_fields = ["LensModel", "LensMake", "LensSpecification"]
        has_lens = any(field in exif_data for field in lens_fields)
        max_score += 0.1
        if has_lens:
            score += 0.1

        # 5. GPS Info Exists (Strong evidence of real shooting)
        gps_fields = ["GPSLatitude", "GPSLongitude", "GPSAltitude"]
        has_gps = any(field in exif_data for field in gps_fields)
        max_score += 0.15
        if has_gps:
            score += 0.15

        # 6. Thumbnail Exists (Camera generates automatically)
        thumbnail_fields = ["ThumbnailImage", "JPEGThumbnail"]
        has_thumbnail = any(field in exif_data for field in thumbnail_fields)
        max_score += 0.05
        if has_thumbnail:
            score += 0.05

        # 7. Color Space Info
        color_fields = ["ColorSpace", "WhiteBalance"]
        has_color = any(field in exif_data for field in color_fields)
        max_score += 0.05
        if has_color:
            score += 0.05

        # Normalization
        return score / max_score if max_score > 0 else 0.0

    def _detect_exif_inconsistencies(
        self, exif_data: Optional[Dict[str, Any]]
    ) -> List[str]:
        """
        Detect Abnormal EXIF Data Patterns
        AI-generated images often have incomplete or manipulated EXIF
        """
        inconsistencies = []

        if not exif_data:
            return inconsistencies

        # 1. Software field contains editing tool but no camera info
        has_software = "Software" in exif_data
        has_camera = "Make" in exif_data or "Model" in exif_data

        if has_software and not has_camera:
            software = str(exif_data["Software"]).lower()
            editing_tools = ["photoshop", "gimp", "pixelmator", "affinity", "paint"]
            if any(tool in software for tool in editing_tools):
                inconsistencies.append("editing_software_without_camera")

        # 2. Image size is exactly square/specific ratio (AI generation characteristic)
        # 512x512, 768x768, 1024x1024 etc.
        if "ExifImageWidth" in exif_data and "ExifImageHeight" in exif_data:
            width = exif_data["ExifImageWidth"]
            height = exif_data["ExifImageHeight"]
            if isinstance(width, int) and isinstance(height, int):
                if width == height and width in [512, 768, 1024, 2048]:
                    inconsistencies.append("perfect_square_ai_resolution")

        # 3. Unrealistic shooting settings
        if "FNumber" in exif_data:
            f_number = exif_data["FNumber"]
            # F-number abnormally small or large
            if isinstance(f_number, (int, float)) and (f_number < 0.5 or f_number > 64):
                inconsistencies.append("unrealistic_aperture")

        # 4. DateTime exists but DateTimeOriginal missing (Suspicious)
        has_datetime = "DateTime" in exif_data
        has_original = "DateTimeOriginal" in exif_data
        if has_datetime and not has_original and has_camera:
            inconsistencies.append("missing_datetime_original")

        return inconsistencies

    def has_ai_indicators(self, metadata_result: Dict[str, Any]) -> bool:
        """Check if AI generation indicators exist"""
        # If C2PA contains AI related info
        if metadata_result.get("has_c2pa"):
            c2pa_info = metadata_result.get("c2pa_info", {})
            if c2pa_info.get("ai_related_assertions"):
                return True

        # If AI tool signature found
        if metadata_result.get("ai_tool_signatures"):
            return True

        # If EXIF contains AI related info
        exif = metadata_result.get("exif_data", {})
        if exif.get("sd_parameters"):  # Stable Diffusion
            return True

        return False
